### ISSUE TITLE
Mark assignment 3 of <Christina><Rasnake>

### ISSUE THREAD

**Issue by crasnake** [crasnake/week_03#1]
0c99273

@rharrington31

**Comment by rharrington31** [comment]
1. Good.
2. Good.
3. `summary` is a good approach to get started here. I'm looking to see histograms, counts, bar charts, etc. of each field to really get an understanding of the dataset.
4. Right now this assigns `FALSE` to every observation in the dataset. You need to create a conditional statement as part of the `mutate` to appropriately evaluate each observation.
5. Good! No need for the `filter` though!
6. You would need to calculate the top makes first. From there you can assign those to a vector and use them as a filter.
7. Good!
8. Interesting question. I think that this fits well for the purposes of this project. If you need help with de-identification let me know. There's lots of good strategies to do that.
